AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for a full-featured EKS cluster

Parameters:
  ClusterName:
    Type: String
    Description: Name for the EKS cluster

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where the EKS cluster will be created

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets where the EKS cluster will be created

  ClusterVersion:
    Type: String
    Description: Version of the EKS cluster
    Default: '1.21'

  NodeGroupName:
    Type: String
    Description: Name for the EKS node group

  NodeGroupVersion:
    Type: String
    Description: Version of the EKS node group
    Default: '1.21'

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of the EC2 Key Pair for SSH access to the EKS nodes

  InstanceType:
    Type: String
    Description: EC2 instance type for the EKS nodes
    Default: 't3.medium'

Resources:
  Cluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref ClusterVersion
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref ClusterControlPlaneSecurityGroup
        SubnetIds: !Ref SubnetIds

  NodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Ref NodeGroupName
      Subnets: !Ref SubnetIds
      InstanceTypes:
        - !Ref InstanceType
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      ReleaseVersion: !Ref NodeGroupVersion
      RemoteAccess:
        Ec2SshKey: !Ref KeyPairName

  ClusterControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security group for the EKS cluster control plane
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  ClusterNameOutput:
    Description: Name of the EKS cluster
    Value: !Ref ClusterName

  ClusterEndpoint:
    Description: Endpoint URL of the EKS cluster
    Value: !GetAtt Cluster.Endpoint

  NodegroupNameOutput:
    Description: Name of the EKS node group
    Value: !Ref NodeGroupName

  NodeGroupArn:
    Description: ARN of the EKS node group
    Value: !GetAtt NodeGroup.NodeGroupArn
